#!/bin/bash

cp dot_vimrc ~/.vimrc

cp dot_xsessionrc ~/.xsessionrc

rsync -av --delete --progress --stats dot_config/awesome/ ~/.config/awesome

rsync -av --delete --progress --stats dot_vim/ ~/.vim

#rsync -av --delete --progress --stats dot_profile.d/ ~/.profile.d

#cp sources.list.d/* /etc/apt/sources.list.d

sudo -k cp bin/awesome-spawn-once /usr/local/bin


